sudo: required 
services:
  - docker

before_install:
  - docker build -t aamrr/devopsssignment -f Dockerfile.dev .
script:
  - export CHROME_BIN='/usr/bin/chromium'
  - docker run -d aamrr/devopsssignment

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: devopsssignment
  on: master