sudo: required 
services:
  - docker

before_install:
  - docker build -t aamrr/devopsssignment -f Dockerfile.dev .
script:
  - docker run aamrr/devopsssignment npm run test -- --watch false  

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: devopsssignment
  on: master