sudo: required 
services:
  - docker

before_install:
  - docker build -t aamrr/devopsssignment -f Dockerfile.dev .
script:
  - docker run -d -p 80:4200 aamrr/devopsssignment

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: devopsssignment
  on: master